In [6]:
from model_profiles_pfk import model_init, model_prof
import numpy as np

In [15]:
init_guess, ranges = model_init('twodgaussring')
init_guess = np.array(init_guess)
ranges = np.array(ranges)

In [16]:
init_guess

array([ 6,  1,  7, 60, 15,  0,  0])

In [17]:
nwalkers = 32
ndim = len(ranges)
pos = np.zeros([nwalkers, ndim])

In [18]:
def log_prior(pars, ranges):
    """
    Calculates the flat log-prior probability for the current parameter set.

    Args:
        pars (np.ndarray): 1D vector of model parameters to be sampled.
        ranges (np.ndarray): 2D vector of boundary constraints for the prior.

    Returns:
        float: 0.0 if all parameters are within bounds, -np.inf otherwise.
    """

    if np.any((pars <= ranges[:, 0]) | (pars >= ranges[:, 1])):
        return -np.inf
    return 0.0

In [19]:
for i in range(nwalkers):
    c = 0
    while c != 1:
        pos[i, :] = init_guess + 1e-5*np.random.randn(ndim)
        chk_pars = log_prior(pos[i,:], ranges)
        if chk_pars == 0:
            c = 1

In [20]:
pos

array([[ 6.00001734e+00,  1.00001076e+00,  7.00000484e+00,
         5.99999869e+01,  1.50000082e+01,  2.59709305e-05,
        -6.89752142e-06],
       [ 5.99998931e+00,  9.99994738e-01,  6.99997853e+00,
         5.99999875e+01,  1.50000071e+01,  5.63817747e-06,
         1.58191404e-05],
       [ 6.00000850e+00,  1.00000257e+00,  7.00000579e+00,
         6.00000005e+01,  1.50000070e+01,  3.92857151e-06,
         1.17495721e-05],
       [ 5.99996698e+00,  1.00000366e+00,  7.00001974e+00,
         5.99999990e+01,  1.49999769e+01,  8.29033576e-06,
         7.19184034e-06],
       [ 5.99999339e+00,  9.99993032e-01,  7.00000927e+00,
         6.00000088e+01,  1.50000017e+01, -9.49695076e-06,
        -2.72944466e-06],
       [ 5.99998744e+00,  9.99998562e-01,  7.00000522e+00,
         6.00000046e+01,  1.49999964e+01, -6.64024610e-06,
         2.19656363e-07],
       [ 6.00000982e+00,  1.00000544e+00,  6.99998042e+00,
         6.00000153e+01,  1.50000213e+01, -1.53617571e-06,
        -1.1168880

In [23]:
for i in range(nwalkers):
    c = 0
    while c != 1:
        pos[i, 0] = np.random.normal(init_guess[0], 0.06)
        pos[i, 1] = np.random.normal(init_guess[1], 0.15)
        pos[i, 2] = np.random.normal(init_guess[2], 0.15)
        pos[i, 3] = np.random.normal(init_guess[3], 1.5)
        pos[i, 4] = np.random.normal(init_guess[4], 1.5)
        pos[i, 5] = np.random.normal(init_guess[5], 0.15)
        pos[i, 6] = np.random.normal(init_guess[6], 0.15)
        chk_pars = log_prior(pos[i,:], ranges)
        if chk_pars == 0:
            c = 1

In [25]:
init_guess

array([ 6,  1,  7, 60, 15,  0,  0])

In [26]:
ranges

array([[ -5,  15],
       [  0,  10],
       [  0,  20],
       [  0,  90],
       [  0, 180],
       [ -5,   5],
       [ -5,   5]])

In [24]:
pos

array([[ 5.97470901e+00,  9.79863826e-01,  6.78778624e+00,
         5.87365731e+01,  1.61067611e+01, -1.21854387e-01,
         1.71124559e-01],
       [ 5.98935306e+00,  1.12998869e+00,  6.85116041e+00,
         5.77485048e+01,  1.36152587e+01,  5.72711429e-02,
        -2.48202366e-01],
       [ 6.09979669e+00,  1.03156352e+00,  6.91447194e+00,
         5.89818903e+01,  1.54261950e+01,  2.40533286e-01,
        -1.18240589e-01],
       [ 5.95512894e+00,  1.07684959e+00,  6.97462412e+00,
         6.03678513e+01,  1.58061953e+01,  2.82327520e-02,
         1.42873995e-01],
       [ 5.96147370e+00,  1.21378047e+00,  6.92736494e+00,
         6.01003531e+01,  1.15994891e+01,  9.51650619e-02,
         1.17100538e-02],
       [ 6.09786991e+00,  1.21277319e+00,  6.95775885e+00,
         6.01205268e+01,  1.50139296e+01,  3.42816638e-01,
         9.45326462e-02],
       [ 5.95719965e+00,  7.23659595e-01,  6.88874171e+00,
         6.04013677e+01,  1.72882646e+01, -1.30882782e-01,
        -2.9673174

In [27]:
ranges

array([[ -5,  15],
       [  0,  10],
       [  0,  20],
       [  0,  90],
       [  0, 180],
       [ -5,   5],
       [ -5,   5]])

In [35]:
np.random.uniform(ranges[1][0], ranges[1][1])

8.43020675435063

In [36]:
for i in range(nwalkers):
    c = 0
    while c != 1:
        pos[i, 0] = np.random.uniform(ranges[0][0], ranges[0][1])
        pos[i, 1] = np.random.uniform(ranges[1][0], ranges[1][1])
        pos[i, 2] = np.random.uniform(ranges[2][0], ranges[2][1])
        pos[i, 3] = np.random.uniform(ranges[3][0], ranges[3][1])
        pos[i, 4] = np.random.uniform(ranges[4][0], ranges[4][1])
        pos[i, 5] = np.random.uniform(ranges[5][0], ranges[5][1])
        pos[i, 6] = np.random.uniform(ranges[6][0], ranges[6][1])
        chk_pars = log_prior(pos[i,:], ranges)
        if chk_pars == 0:
            c = 1

In [37]:
pos

array([[ 1.16087626e+01,  5.22295252e+00,  1.73825264e+00,
         8.72931540e+01,  1.68751384e+02,  1.09802808e-02,
        -9.16091348e-02],
       [ 1.15946275e+01,  4.23757189e-01,  1.15016227e+01,
         6.50812942e+01,  7.02844568e+01, -3.42531073e-01,
         8.23146803e-01],
       [-1.12299213e-01,  9.18666699e+00,  5.05451992e+00,
         5.13925377e+01,  9.00055891e+01,  2.07545192e-01,
        -2.10472620e+00],
       [ 9.61230140e+00,  4.13199965e+00,  1.33004478e+01,
         7.56347962e+01,  2.33557050e+00, -1.20987023e+00,
         4.12709995e+00],
       [ 4.33757782e+00,  5.24244114e+00,  4.60760294e+00,
         8.53722908e+01,  8.84876663e+01, -2.69935574e+00,
         4.95799185e+00],
       [ 1.02118041e+00,  7.09613554e-02,  1.25783809e+01,
         7.53062495e+01,  1.39786719e+02, -9.82384958e-01,
        -3.04747472e+00],
       [ 3.29670477e+00,  5.60187365e+00,  6.66535161e+00,
         6.23315825e+01,  1.42145878e+02, -4.29523812e+00,
         2.7991450